// 自动生成，勿手改（scripts/build-scene-images.mjs）
import type { ImageSourcePropType } from 'react-native';

export const SCENE_IMAGES: Record<string, ImageSourcePropType> = {
  'cn-civil-001': require('../assets/images/cn-civil-001.jpg'),
  'cn-civil-002': require('../assets/images/cn-civil-002.jpg'),
  'cn-adult-001': require('../assets/images/cn-adult-001.jpg'),
  'cn-adult-002': require('../assets/images/cn-adult-002.jpg'),
  'cn-adult-003': require('../assets/images/cn-adult-003.jpg'),
  'cn-adult-004': require('../assets/images/cn-adult-004.jpg'),
  'cn-adult-005': require('../assets/images/cn-adult-005.jpg'),
  'cn-mid-001': require('../assets/images/cn-mid-001.jpg'),
  'cn-mid-002': require('../assets/images/cn-mid-002.jpg'),
  'cn-mid-003': require('../assets/images/cn-mid-003.jpg'),
  'cn-senior-001': require('../assets/images/cn-senior-001.jpg'),
  'cn-senior-002': require('../assets/images/cn-senior-002.jpg'),
  'cn-senior-003': require('../assets/images/cn-senior-003.jpg'),
  'cn-senior-004': require('../assets/images/cn-senior-004.jpg'),
  'cn-shop-001': require('../assets/images/cn-shop-001.jpg'),
  'cn-shop-002': require('../assets/images/cn-shop-002.jpg'),
  'cn-job-001': require('../assets/images/cn-job-001.jpg'),
  'cn-job-002': require('../assets/images/cn-job-002.jpg'),
  'cn-job-003': require('../assets/images/cn-job-003.jpg'),
  'cn-kid-001': require('../assets/images/cn-kid-001.jpg'),
  'cn-kid-002': require('../assets/images/cn-kid-002.jpg'),
  'cn-kid-003': require('../assets/images/cn-kid-003.jpg'),
  'cn-kid-004': require('../assets/images/cn-kid-004.jpg'),
  'cn-teen-001': require('../assets/images/cn-teen-001.jpg'),
  'cn-teen-002': require('../assets/images/cn-teen-002.jpg'),
  'cn-teen-003': require('../assets/images/cn-teen-003.jpg'),
  'cn-teen-004': require('../assets/images/cn-teen-004.jpg'),
  'cn-traffic-001': require('../assets/images/cn-traffic-001.jpg'),
  'cn-traffic-002': require('../assets/images/cn-traffic-002.jpg'),
  'cn-traffic-003': require('../assets/images/cn-traffic-003.jpg'),
  'us-job-001': require('../assets/images/us-job-001.jpg'),
  'us-job-002': require('../assets/images/us-job-002.jpg'),
  'us-shop-001': require('../assets/images/us-shop-001.jpg'),
  'us-rent-001': require('../assets/images/us-rent-001.jpg'),
  'us-traffic-001': require('../assets/images/us-traffic-001.jpg'),
  'us-teen-001': require('../assets/images/us-teen-001.jpg'),
  'eu-data-001': require('../assets/images/eu-data-001.jpg'),
  'eu-data-002': require('../assets/images/eu-data-002.jpg'),
  'eu-data-003': require('../assets/images/eu-data-003.jpg'),
  'eu-data-004': require('../assets/images/eu-data-004.jpg'),
  'eu-data-005': require('../assets/images/eu-data-005.jpg'),
};
